### ISSUE TITLE
"proj library not found" on F35/proj8 builds

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/fortrangis#15]
```
checking for pj_init in -lproj... no
configure: error: proj library not found
error: Bad exit status from /var/tmp/rpm-tmp.BlJVHj (%build)
    Bad exit status from /var/tmp/rpm-tmp.BlJVHj (%build)
```

This happens on F35 and later builds, despite having proj-devel (8) installed

Full example log:
https://download.copr.fedorainfracloud.org/results/simc/stable/fedora-35-x86_64/03528692-fortrangis/builder-live.log.gz

**Comment by brancomat** [comment]
Also true for F36 builds:
https://download.copr.fedorainfracloud.org/results/simc/stable/fedora-36-x86_64/04386051-fortrangis/builder-live.log.gz

(this too is probably related to the change of release of proj from 7 to 8)

**Comment by edigiacomo** [comment]
Ho creato la PR #17 per supportare anche proj8, in cui sono cambiate alcune funzioni, tra cui `pj_init`. Il mapping tra nuove e vecchie funzioni è qui https://proj.org/development/migration.html#function-mapping-from-old-to-new-api: servirà per poter compilare fortrangis in fedora >= 35.
