### ISSUE TITLE
Building the library

### ISSUE THREAD

**Issue by bao18** [ARPA-SIMC/fortrangis#3]
Hello,

I having problems to build the libraries in macOS 10.13 using Inter Fortran.
The outputs are shwown bellow,

Thanks in advance.

## ./configure --prefix=/usr/local/FortranGIS

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for X... no
checking for gdal-config... yes
checking for pj_init in -lproj... yes
checking for SHPOpen in -lshp... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking shapefil.h usability... yes
checking shapefil.h presence... yes
checking for shapefil.h... yes
checking whether we are using the GNU Fortran compiler... no
checking whether ifort accepts -g... yes
checking for Fortran flag to compile .f90 files... none
Fortran 2003 C bindings found!
checking for doxygen... yes
checking build system type... x86_64-apple-darwin17.3.0
checking host system type... x86_64-apple-darwin17.3.0
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin17.3.0 file names to x86_64-apple-darwin17.3.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin17.3.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin17.3.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for ifort option to produce PIC... -fno-common
checking if ifort PIC flag -fno-common works... yes
checking if ifort static flag  works... yes
checking if ifort supports -c -o file.o... yes
checking if ifort supports -c -o file.o... (cached) yes
checking whether the ifort linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin17.3.0 dyld
checking how to hardcode library paths into programs... immediate
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libfortranc/Makefile
config.status: creating libfortrangis/Makefile
config.status: creating doc/Doxyfile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

## make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in libfortranc
/bin/sh ../libtool  --tag=FC   --mode=compile ifort -DHAVE_CONFIG_H -I. -I..     -g -O -c -o fortranc.lo fortranc.F90
libtool: compile:  ifort -DHAVE_CONFIG_H -I. -I.. -g -O -c fortranc.F90  -fno-common -o .libs/fortranc.o
libtool: compile:  ifort -DHAVE_CONFIG_H -I. -I.. -g -O -c fortranc.F90 -o fortranc.o >/dev/null 2>&1
/bin/sh ../libtool  --tag=FC   --mode=link ifort  -g -O -version-info 2:6  -o libfortranc.la -rpath /usr/local/FortranGIS/lib fortranc.lo  
libtool: link: ifort -dynamiclib -undefined dynamic_lookup -o .libs/libfortranc.2.dylib  .libs/fortranc.o    -g -O   -install_name  /usr/local/FortranGIS/lib/libfortranc.2.dylib -compatibility_version 3 -current_version 3.6 -single_module
libtool: link: (cd ".libs" && rm -f "libfortranc.dylib" && ln -s "libfortranc.2.dylib" "libfortranc.dylib")
libtool: link: ar cru .libs/libfortranc.a  fortranc.o
libtool: link: ranlib .libs/libfortranc.a
libtool: link: ( cd ".libs" && rm -f "libfortranc.la" && ln -s "../libfortranc.la" "libfortranc.la" )
Making all in libfortrangis
/bin/sh ../libtool  --tag=FC   --mode=compile ifort -DHAVE_CONFIG_H -I. -I..  -I../libfortranc -I../include   -g -O -c -o libfortrangis_la-shapelib.lo `test -f 'shapelib.F90' || echo './'`shapelib.F90
libtool: compile:  ifort -DHAVE_CONFIG_H -I. -I.. -I../libfortranc -I../include -g -O -c shapelib.F90  -fno-common -o .libs/libfortrangis_la-shapelib.o
libtool: compile:  ifort -DHAVE_CONFIG_H -I. -I.. -I../libfortranc -I../include -g -O -c shapelib.F90 -o libfortrangis_la-shapelib.o >/dev/null 2>&1
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../libfortranc -I../include   -g -O2 -O -MT libfortrangis_la-shapelibint.lo -MD -MP -MF .deps/libfortrangis_la-shapelibint.Tpo -c -o libfortrangis_la-shapelibint.lo `test -f 'shapelibint.c' || echo './'`shapelibint.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../libfortranc -I../include -g -O2 -O -MT libfortrangis_la-shapelibint.lo -MD -MP -MF .deps/libfortrangis_la-shapelibint.Tpo -c shapelibint.c  -fno-common -DPIC -o .libs/libfortrangis_la-shapelibint.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../libfortranc -I../include -g -O2 -O -MT libfortrangis_la-shapelibint.lo -MD -MP -MF .deps/libfortrangis_la-shapelibint.Tpo -c shapelibint.c -o libfortrangis_la-shapelibint.o >/dev/null 2>&1
mv -f .deps/libfortrangis_la-shapelibint.Tpo .deps/libfortrangis_la-shapelibint.Plo
/bin/sh ../libtool  --tag=FC   --mode=compile ifort -DHAVE_CONFIG_H -I. -I..  -I../libfortranc -I../include   -g -O -c -o libfortrangis_la-proj.lo `test -f 'proj.F90' || echo './'`proj.F90
libtool: compile:  ifort -DHAVE_CONFIG_H -I. -I.. -I../libfortranc -I../include -g -O -c proj.F90  -fno-common -o .libs/libfortrangis_la-proj.o
libtool: compile:  ifort -DHAVE_CONFIG_H -I. -I.. -I../libfortranc -I../include -g -O -c proj.F90 -o libfortrangis_la-proj.o >/dev/null 2>&1
/bin/sh ../libtool  --tag=FC   --mode=compile ifort -DHAVE_CONFIG_H -I. -I..  -I../libfortranc -I../include   -g -O -c -o libfortrangis_la-gdal.lo `test -f 'gdal.F90' || echo './'`gdal.F90
libtool: compile:  ifort -DHAVE_CONFIG_H -I. -I.. -I../libfortranc -I../include -g -O -c gdal.F90  -fno-common -o .libs/libfortrangis_la-gdal.o
libtool: compile:  ifort -DHAVE_CONFIG_H -I. -I.. -I../libfortranc -I../include -g -O -c gdal.F90 -o libfortrangis_la-gdal.o >/dev/null 2>&1
/bin/sh ../libtool  --tag=FC   --mode=link ifort  -g -O -version-info 2:6 -no-undefined -L/usr/local/Cellar/gdal/1.11.5_3/lib -lgdal  -o libfortrangis.la -rpath /usr/local/FortranGIS/lib libfortrangis_la-shapelib.lo libfortrangis_la-shapelibint.lo libfortrangis_la-proj.lo libfortrangis_la-gdal.lo  ../libfortranc/libfortranc.la -lshp -lproj -L/usr/local/Cellar/gdal/1.11.5_3/lib -lgdal  
libtool: link: ifort -dynamiclib  -o .libs/libfortrangis.2.dylib  .libs/libfortrangis_la-shapelib.o .libs/libfortrangis_la-shapelibint.o .libs/libfortrangis_la-proj.o .libs/libfortrangis_la-gdal.o   -L/usr/local/Cellar/gdal/1.11.5_3/lib ../libfortranc/.libs/libfortranc.dylib -lshp /usr/local/Cellar/proj/4.9.3/lib/libproj.dylib -lpthread -lm -lgdal  -g -O   -install_name  /usr/local/FortranGIS/lib/libfortrangis.2.dylib -compatibility_version 3 -current_version 3.6 -single_module
ld: library not found for -lshp
make[2]: *** [libfortrangis.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by dcesari** [comment]
Hi, it seems that there are some problems in locating the shapelib library when linking the final fortrangis library, on the other hand the preliminary test on shapelib is successful:
```
checking for SHPOpen in -lshp... yes
```
so it's hard to tell the real reason from this, the complete error message should be somewhere towards the end of the file `config.log`, in case please attach that file too. Could you also tell me where the shapelib library (libshp.*) is located? I have no experience on MacOS, so I cannot test myself.
