### ISSUE TITLE
Compilation with nagfor

### ISSUE THREAD

**Issue by lguez** [ARPA-SIMC/fortrangis#4]
In the file libfortrangis/Makefile.am, the following lines should be added inside the "if SHP" test:

ung2shp_FCFLAGS = -I../libfortranc
shapelib_dump_FCFLAGS = -I../libfortranc
shp_fxtr_FCFLAGS = -I../libfortranc

Also, in the files ung2shp.F90, shapelib_dump.F90 and shp_fxtr.F90, the calls to getarg (non-standard Fortran intrinsic) should be replaced by calls to get_command_argument (standard Fortran 2003). The arguments in these calls should not be changed.

Without these changes, the compilation with the NAG Fortran compiler fails. With these changes, it succeeds. I think these changes should be made anyway.

**Comment by dcesari** [comment]
Thank you for pointing that out, I pushed a couple of patches; for FCFLAGS I had to do it in a slightly different way because of another bug appearing, so if you have a chance to try it, please confirm me that it works.

**Comment by lguez** [comment]
Thank you. I checked with your latest commit: compilation works with nagfor, gfortran and ifort.

**Comment by dcesari** [comment]
Great!
